version: v1.0
name: Production-Deploy
agent:
  machine:
    type: s1-agent-c6g-large
    os_image: ''
blocks:
  - name: Deploy Assets
    task:
      jobs:
        - name: Deploy Assets to S3 and Invalidate CloudFront Cache
          commands:
            - artifact pull workflow clevertap.min.js
            - |
              set -euo pipefail
              mkdir utils
              aws s3 cp s3://semaphore-agent-customres-semaphoredependenciess3b-okhz8b8lstnx/utils/generate_assumed_role_creds.py utils/generate_assumed_role_creds.py
              aws s3 cp s3://semaphore-agent-customres-semaphoredependenciess3b-okhz8b8lstnx/uv/uv-aarch64-unknown-linux-gnu.tar.gz - | tar -v -xz -C utils/
              export PATH="$PATH:$(pwd)/utils/uv-aarch64-unknown-linux-gnu"
              uv venv prod
              source prod/bin/activate
              uv pip install argparse PyJWT requests cryptography pytablewriter pyyaml boto3   
              eval $(python3 utils/generate_assumed_role_creds.py --role-arn ${PRODUCTION_ACCOUNT_IAM_ROLE_ARN} --session-name SemaphoreAgent)
              aws s3 cp clevertap.min.js s3://static.wizrocket.com/js/ --acl public-read
              rm -r clevertap.min.js
              aws cloudfront create-invalidation --distribution-id E1OCAMMKX0F1A1 --paths /js/clevertap.min.js
              deactivate
      secrets:
        - name: ProductionAccountAwsCredentials
      agent:
        machine:
          type: s1-agent-c6g-large
          os_image: ''
