version: v1.0
name: Production-Deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
blocks:
  - name: Deploy Assets
    task:
      jobs:
        - name: Deploy Assets to S3 and Invalidate CloudFront Cache
          commands:
            - artifact pull workflow clevertap.min.js
            - |
              mkdir utils
              aws s3 cp s3://cfstack-init-sources3bucket-b5bxfzywj4ae/utils/generate_assumed_role_creds.py utils/generate_assumed_role_creds.py
              eval $(python3 utils/generate_assumed_role_creds.py --role-arn ${PRODUCTION_ACCOUNT_IAM_ROLE_ARN} --session-name SemaphoreAgent)
              env | grep AWS
              aws sts get-caller-identity
            - 'aws s3 cp clevertap.min.js s3://static.wizrocket.com/js/ --acl public-read'
            - rm -r clevertap.min.js
            - aws cloudfront create-invalidation --distribution-id E1OCAMMKX0F1A1 --paths /js/clevertap.min.js
      secrets:
        - name: ProductionAccountAwsCredentials
      agent:
        machine:
          type: s1-ultron-c5-large
          os_image: ''
